In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(f"M87SED_Prieto_quiet_Jy.csv", delimiter=",")
df[::-1]

,Instrument,Frequency_Hz,Angular_Scale_arcsec,Fnu_Jy,sigma_Fnu_Jy
33,VLA-A (Nagar et al. 2001),5.000000e+09,0.4,3.100000e+00,6.000000e-02
32,VLA-A avg,8.400000e+09,0.4,3.020000e+00,2.000000e-02
31,VLA-A,8.400000e+09,0.4,3.150000e+00,1.600000e-01
30,VLA-A avg,1.500000e+10,0.4,2.700000e+00,1.000000e-01
29,VLA-A,2.200000e+10,0.4,2.000000e+00,1.000000e-01
28,ALMA,9.370000e+10,0.4,1.820000e+00,6.000000e-02
27,ALMA,1.080000e+11,0.4,1.910000e+00,5.000000e-02
26,ALMA,2.210000e+11,0.4,1.630000e+00,3.000000e-02
25,ALMA,2.520000e+11,0.4,1.420000e+00,2.000000e-02
24,ALMA,2.860000e+11,0.4,1.280000e+00,2.000000e-02
23,ALMA,3.500000e+11,0.4,9.600000e-01,2.000000e-02
22,ALMA,6.350000e+11,0.4,4.300000e-01,9.000000e-02
21,Keck 11.7um (Whysong & Antonucci 2004),2.600000e+13,0.4,1.300000e-02,2.000000e-03
20,Gemini 10.8um (Perlman et al. 2001),2.800000e+13,0.4,1.670000e-02,9.000000e-04
19,NIC3 F222M,1.370000e+14,0.4,3.300000e-03,6.000000e-04
18,NIC3 F166N,1.810000e+14,0.4,3.100000e-03,8.000000e-04
17,NIC2 F110W,2.470000e+14,0.4,2.060000e-03,1.800000e-04
16,ACS-WFC F850LP,3.320000e+14,0.4,1.380000e-03,1.000000e-05
15,ACS-HRC F814W,3.700000e+14,0.4,9.500000e-04,1.900000e-04
14,ACS-HRC F606W,4.990000e+14,0.4,6.330000e-04,6.300000e-05
13,ACS-HRC F475W,6.320000e+14,0.4,4.130000e-04,1.200000e-05
12,ACS-HRC F330W,8.930000e+14,0.4,2.100000e-04,4.000000e-06
11,ACS-HRC F330W,8.930000e+14,0.4,2.160000e-04,4.000000e-06
10,ACS-HRC F250W,1.110000e+15,0.4,1.550000e-04,3.000000e-06
9,STIS-F25QTZ,1.270000e+15,0.4,1.050000e-04,3.000000e-06
8,ACS-HRC F220W,1.360000e+15,0.4,1.330000e-04,4.000000e-06
7,STIS-F25SRF2,2.060000e+15,0.4,4.730000e-05,4.700000e-06
6,Chandra avg (00 & 02),2.420000e+17,0.4,2.500000e-07,1.250000e-07
5,Chandra,2.420000e+17,0.4,2.000000e-07,1.000000e-08
4,Chandra (Di Matteo et al. 2003),2.420000e+17,0.4,3.100000e-07,9.000000e-09
3,Chandra avg (00 & 02),2.420000e+18,0.4,2.300000e-08,1.200000e-08
2,Chandra,2.420000e+18,0.4,2.800000e-08,3.600000e-09
1,Chandra (Di Matteo et al. 2003),2.420000e+18,0.4,1.800000e-08,2.300000e-09
0,HESS,2.420000e+26,0.4,1.600000e-07,1.000000e-07

In [3]:
df["nuFnu_1e-12ergscm2"] = df["Fnu_Jy"] * 1e-23 * df["Frequency_Hz"] * 1e12
df["sigma_nuFnu_1e-12ergscm2"] = df["sigma_Fnu_Jy"] * 1e-23 * df["Frequency_Hz"] * 1e12

df_rev = df.iloc[::-1]
df_new = df_rev[["Instrument", "Frequency_Hz", "Angular_Scale_arcsec", "nuFnu_1e-12ergscm2", "sigma_nuFnu_1e-12ergscm2"]]
df_new

,Instrument,Frequency_Hz,Angular_Scale_arcsec,nuFnu_1e-12ergscm2,sigma_nuFnu_1e-12ergscm2
33,VLA-A (Nagar et al. 2001),5.000000e+09,0.4,1.550000e-01,3.000000e-03
32,VLA-A avg,8.400000e+09,0.4,2.536800e-01,1.680000e-03
31,VLA-A,8.400000e+09,0.4,2.646000e-01,1.344000e-02
30,VLA-A avg,1.500000e+10,0.4,4.050000e-01,1.500000e-02
29,VLA-A,2.200000e+10,0.4,4.400000e-01,2.200000e-02
28,ALMA,9.370000e+10,0.4,1.705340e+00,5.622000e-02
27,ALMA,1.080000e+11,0.4,2.062800e+00,5.400000e-02
26,ALMA,2.210000e+11,0.4,3.602300e+00,6.630000e-02
25,ALMA,2.520000e+11,0.4,3.578400e+00,5.040000e-02
24,ALMA,2.860000e+11,0.4,3.660800e+00,5.720000e-02
23,ALMA,3.500000e+11,0.4,3.360000e+00,7.000000e-02
22,ALMA,6.350000e+11,0.4,2.730500e+00,5.715000e-01
21,Keck 11.7um (Whysong & Antonucci 2004),2.600000e+13,0.4,3.380000e+00,5.200000e-01
20,Gemini 10.8um (Perlman et al. 2001),2.800000e+13,0.4,4.676000e+00,2.520000e-01
19,NIC3 F222M,1.370000e+14,0.4,4.521000e+00,8.220000e-01
18,NIC3 F166N,1.810000e+14,0.4,5.611000e+00,1.448000e+00
17,NIC2 F110W,2.470000e+14,0.4,5.088200e+00,4.446000e-01
16,ACS-WFC F850LP,3.320000e+14,0.4,4.581600e+00,3.320000e-02
15,ACS-HRC F814W,3.700000e+14,0.4,3.515000e+00,7.030000e-01
14,ACS-HRC F606W,4.990000e+14,0.4,3.158670e+00,3.143700e-01
13,ACS-HRC F475W,6.320000e+14,0.4,2.610160e+00,7.584000e-02
12,ACS-HRC F330W,8.930000e+14,0.4,1.875300e+00,3.572000e-02
11,ACS-HRC F330W,8.930000e+14,0.4,1.928880e+00,3.572000e-02
10,ACS-HRC F250W,1.110000e+15,0.4,1.720500e+00,3.330000e-02
9,STIS-F25QTZ,1.270000e+15,0.4,1.333500e+00,3.810000e-02
8,ACS-HRC F220W,1.360000e+15,0.4,1.808800e+00,5.440000e-02
7,STIS-F25SRF2,2.060000e+15,0.4,9.743800e-01,9.682000e-02
6,Chandra avg (00 & 02),2.420000e+17,0.4,6.050000e-01,3.025000e-01
5,Chandra,2.420000e+17,0.4,4.840000e-01,2.420000e-02
4,Chandra (Di Matteo et al. 2003),2.420000e+17,0.4,7.502000e-01,2.178000e-02
3,Chandra avg (00 & 02),2.420000e+18,0.4,5.566000e-01,2.904000e-01
2,Chandra,2.420000e+18,0.4,6.776000e-01,8.712000e-02
1,Chandra (Di Matteo et al. 2003),2.420000e+18,0.4,4.356000e-01,5.566000e-02
0,HESS,2.420000e+26,0.4,3.872000e+08,2.420000e+08

In [4]:
df_new.to_csv("../../M87data/data/SED/M87SED_Prieto_quiet.csv", index=False)